"""
OfficerOfTheWatch agent for Klabautermann.

Proactive alert and monitoring agent that watches for conditions warranting
notification - approaching deadlines, upcoming meetings, schedule conflicts,
and unusual patterns. Respects "quiet mode" during focused work periods.

Reference: specs/architecture/AGENTS_EXTENDED.md Section 3
Issues: #59, #60, #61
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any

from klabautermann.agents.base_agent import BaseAgent
from klabautermann.core.logger import logger
from klabautermann.core.models import AgentMessage


if TYPE_CHECKING:
    from klabautermann.memory.neo4j_client import Neo4jClient


# =============================================================================
# Configuration
# =============================================================================


class AlertPriority(str, Enum):
    """Priority levels for alerts."""

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    """Types of alerts the Officer can generate."""

    MORNING_BRIEFING = "morning_briefing"
    DEADLINE_WARNING = "deadline_warning"
    MEETING_REMINDER = "meeting_reminder"
    SCHEDULE_CONFLICT = "schedule_conflict"
    OVERDUE_TASK = "overdue_task"
    ANOMALY = "anomaly"


@dataclass
class OfficerConfig:
    """Configuration for OfficerOfTheWatch agent."""

    # Timing thresholds
    deadline_warning_hours: int = 24  # Warn when task due within N hours
    meeting_reminder_minutes: int = 15  # Remind N minutes before meeting

    # Deep Work detection
    deep_work_keywords: list[str] = field(
        default_factory=lambda: ["Deep Work", "Focus", "Do Not Disturb"]
    )

    # Alert limits
    max_alerts_per_check: int = 10
    alert_debounce_minutes: int = 60  # Don't re-send same alert within N minutes

    # Query limits
    default_query_limit: int = 50


@dataclass
class Alert:
    """A single alert generated by the Officer."""

    alert_type: AlertType
    priority: AlertPriority
    message: str
    entity_uuid: str | None = None
    entity_type: str | None = None
    due_at: int | None = None  # Unix timestamp (milliseconds)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "alert_type": self.alert_type.value,
            "priority": self.priority.value,
            "message": self.message,
            "entity_uuid": self.entity_uuid,
            "entity_type": self.entity_type,
            "due_at": self.due_at,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class AlertCheckResult:
    """Result of an alert check operation."""

    alerts_found: int
    alerts_sent: int
    quiet_mode: bool
    deep_work_event: str | None
    duration_ms: float
    alerts: list[Alert] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alerts_found": self.alerts_found,
            "alerts_sent": self.alerts_sent,
            "quiet_mode": self.quiet_mode,
            "deep_work_event": self.deep_work_event,
            "duration_ms": round(self.duration_ms, 2),
            "alerts": [a.to_dict() for a in self.alerts],
        }


# =============================================================================
# OfficerOfTheWatch Agent
# =============================================================================


class OfficerOfTheWatch(BaseAgent):
    """
    Proactive alert and monitoring agent.

    The Officer monitors conditions that warrant proactive notification -
    approaching deadlines, upcoming meetings, schedule conflicts, and
    unusual patterns. Respects "quiet mode" during focused work periods.
    """

    def __init__(
        self,
        neo4j_client: Neo4jClient,
        config: OfficerConfig | None = None,
    ) -> None:
        """
        Initialize OfficerOfTheWatch.

        Args:
            neo4j_client: Connected Neo4j client for graph operations.
            config: Optional configuration for alert behavior.
        """
        super().__init__(name="officer_of_the_watch")
        self.neo4j = neo4j_client
        self.officer_config = config or OfficerConfig()

        # Track recently sent alerts for debouncing
        self._recent_alerts: dict[str, datetime] = {}

        # Current quiet mode state
        self._quiet_mode = False
        self._current_deep_work_event: str | None = None

    async def process_message(self, msg: AgentMessage) -> AgentMessage | None:
        """
        Process an incoming message.

        OfficerOfTheWatch responds to monitoring and alert commands.

        Args:
            msg: The incoming agent message.

        Returns:
            Response message with alert results.
        """
        trace_id = msg.trace_id
        payload = msg.payload or {}

        operation = payload.get("operation", "check_conditions")

        logger.info(
            f"[CHART] OfficerOfTheWatch processing {operation}",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        if operation == "check_conditions":
            result = await self.check_conditions(trace_id=trace_id)
            result_payload = result.to_dict()
        elif operation == "check_deadlines":
            alerts = await self.check_upcoming_deadlines(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "check_meetings":
            alerts = await self.check_upcoming_meetings(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "check_overdue":
            alerts = await self.check_overdue_tasks(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "is_deep_work":
            is_deep_work = await self.is_deep_work_time(trace_id=trace_id)
            result_payload = {
                "is_deep_work": is_deep_work,
                "deep_work_event": self._current_deep_work_event,
            }
        else:
            result_payload = {"error": f"Unknown operation: {operation}"}

        return AgentMessage(
            source_agent=self.name,
            target_agent=msg.source_agent,
            intent="officer_result",
            payload=result_payload,
            trace_id=trace_id,
        )

    # =========================================================================
    # Main Operations
    # =========================================================================

    async def check_conditions(
        self,
        trace_id: str | None = None,
    ) -> AlertCheckResult:
        """
        Main monitoring routine - check all alert conditions.

        This is the primary entry point called by scheduler.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            AlertCheckResult with all generated alerts.
        """
        start_time = time.time()
        all_alerts: list[Alert] = []

        logger.info(
            "[CHART] Officer checking conditions",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        # Check if in quiet mode (Deep Work time)
        self._quiet_mode = await self.is_deep_work_time(trace_id=trace_id)

        if self._quiet_mode:
            logger.info(
                f"[WHISPER] Quiet mode active: {self._current_deep_work_event}",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )

        # Run all checks
        deadline_alerts = await self.check_upcoming_deadlines(trace_id=trace_id)
        all_alerts.extend(deadline_alerts)

        meeting_alerts = await self.check_upcoming_meetings(trace_id=trace_id)
        all_alerts.extend(meeting_alerts)

        overdue_alerts = await self.check_overdue_tasks(trace_id=trace_id)
        all_alerts.extend(overdue_alerts)

        # Filter by quiet mode and debouncing
        alerts_to_send: list[Alert] = []
        for alert in all_alerts:
            if self._should_notify(alert):
                alerts_to_send.append(alert)
                self._mark_alert_sent(alert)

        # Limit alerts per check
        alerts_to_send = alerts_to_send[: self.officer_config.max_alerts_per_check]

        duration_ms = (time.time() - start_time) * 1000

        result = AlertCheckResult(
            alerts_found=len(all_alerts),
            alerts_sent=len(alerts_to_send),
            quiet_mode=self._quiet_mode,
            deep_work_event=self._current_deep_work_event,
            duration_ms=duration_ms,
            alerts=alerts_to_send,
        )

        logger.info(
            f"[BEACON] Officer check complete: "
            f"found {len(all_alerts)} alerts, sending {len(alerts_to_send)} "
            f"(quiet_mode={self._quiet_mode})",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return result

    # =========================================================================
    # Deep Work Detection
    # =========================================================================

    async def is_deep_work_time(
        self,
        trace_id: str | None = None,
    ) -> bool:
        """
        Check if the Captain is currently in a Deep Work calendar block.

        Deep Work events are detected by title keywords like "Deep Work",
        "Focus", or "Do Not Disturb".

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            True if in deep work mode, False otherwise.
        """
        keywords = self.officer_config.deep_work_keywords
        # Build regex pattern for keywords
        keyword_pattern = "|".join(keywords)

        query = """
        MATCH (e:Event)
        WHERE e.start_time <= timestamp()
          AND e.end_time >= timestamp()
          AND e.expired_at IS NULL
          AND e.title =~ $pattern
        RETURN e.uuid as uuid, e.title as title
        LIMIT 1
        """

        result = await self.neo4j.execute_query(
            query,
            {"pattern": f"(?i).*({keyword_pattern}).*"},
            trace_id=trace_id,
        )

        if result:
            self._current_deep_work_event = result[0].get("title")
            return True

        self._current_deep_work_event = None
        return False

    # =========================================================================
    # Deadline Alerts (#60)
    # =========================================================================

    async def check_upcoming_deadlines(
        self,
        hours: int | None = None,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find tasks due within the specified time window.

        Generates WARNING alerts for high-priority tasks and INFO alerts
        for normal priority tasks.

        Args:
            hours: Hours until deadline (default from config).
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for upcoming deadlines.
        """
        hours = hours or self.officer_config.deadline_warning_hours
        hours_ms = hours * 60 * 60 * 1000  # Convert to milliseconds

        logger.debug(
            f"[WHISPER] Checking deadlines within {hours} hours",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.due_date IS NOT NULL
          AND t.due_date <= timestamp() + $hours_ms
          AND t.due_date > timestamp()
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.due_date as due_date,
               t.priority as priority, t.status as status,
               p.name as project_name
        ORDER BY t.due_date ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {
                "hours_ms": hours_ms,
                "limit": self.officer_config.default_query_limit,
            },
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            priority = row.get("priority", "medium")
            alert_priority = (
                AlertPriority.WARNING if priority in ("urgent", "high") else AlertPriority.INFO
            )

            # Calculate hours remaining
            due_date = row.get("due_date", 0)
            now_ms = int(time.time() * 1000)
            hours_remaining = (due_date - now_ms) / (60 * 60 * 1000)

            message = f"Task due in {hours_remaining:.1f}h: {row.get('action', 'Unknown task')}"
            if row.get("project_name"):
                message += f" ({row['project_name']})"

            alert = Alert(
                alert_type=AlertType.DEADLINE_WARNING,
                priority=alert_priority,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Task",
                due_at=due_date,
                metadata={
                    "task_action": row.get("action"),
                    "task_priority": priority,
                    "task_status": row.get("status"),
                    "project_name": row.get("project_name"),
                    "hours_remaining": round(hours_remaining, 1),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} deadline warnings",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Meeting Reminders (#61)
    # =========================================================================

    async def check_upcoming_meetings(
        self,
        minutes: int | None = None,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find meetings starting within the specified time window.

        Generates INFO alerts for upcoming meetings with event details.

        Args:
            minutes: Minutes until meeting (default from config).
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for upcoming meetings.
        """
        minutes = minutes or self.officer_config.meeting_reminder_minutes
        minutes_ms = minutes * 60 * 1000  # Convert to milliseconds

        logger.debug(
            f"[WHISPER] Checking meetings within {minutes} minutes",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (e:Event)
        WHERE e.start_time <= timestamp() + $minutes_ms
          AND e.start_time > timestamp()
          AND e.expired_at IS NULL
        RETURN e.uuid as uuid, e.title as title, e.start_time as start_time,
               e.end_time as end_time, e.location_context as location,
               e.description as description
        ORDER BY e.start_time ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {
                "minutes_ms": minutes_ms,
                "limit": self.officer_config.default_query_limit,
            },
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            # Calculate minutes remaining
            start_time = row.get("start_time", 0)
            now_ms = int(time.time() * 1000)
            minutes_remaining = (start_time - now_ms) / (60 * 1000)

            message = (
                f"Meeting in {minutes_remaining:.0f}min: {row.get('title', 'Unknown meeting')}"
            )
            if row.get("location"):
                message += f" at {row['location']}"

            alert = Alert(
                alert_type=AlertType.MEETING_REMINDER,
                priority=AlertPriority.INFO,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Event",
                due_at=start_time,
                metadata={
                    "event_title": row.get("title"),
                    "event_location": row.get("location"),
                    "event_description": row.get("description"),
                    "start_time": start_time,
                    "end_time": row.get("end_time"),
                    "minutes_remaining": round(minutes_remaining, 0),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} meeting reminders",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Overdue Tasks
    # =========================================================================

    async def check_overdue_tasks(
        self,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find tasks that are past their due date.

        Generates ERROR alerts for overdue tasks.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for overdue tasks.
        """
        logger.debug(
            "[WHISPER] Checking overdue tasks",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.due_date IS NOT NULL
          AND t.due_date < timestamp()
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.due_date as due_date,
               t.priority as priority, t.status as status,
               p.name as project_name
        ORDER BY t.due_date ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {"limit": self.officer_config.default_query_limit},
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            # Calculate hours overdue
            due_date = row.get("due_date", 0)
            now_ms = int(time.time() * 1000)
            hours_overdue = (now_ms - due_date) / (60 * 60 * 1000)

            message = f"Task overdue by {hours_overdue:.1f}h: {row.get('action', 'Unknown task')}"
            if row.get("project_name"):
                message += f" ({row['project_name']})"

            alert = Alert(
                alert_type=AlertType.OVERDUE_TASK,
                priority=AlertPriority.ERROR,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Task",
                due_at=due_date,
                metadata={
                    "task_action": row.get("action"),
                    "task_priority": row.get("priority"),
                    "task_status": row.get("status"),
                    "project_name": row.get("project_name"),
                    "hours_overdue": round(hours_overdue, 1),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} overdue tasks",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Alert Filtering and Debouncing
    # =========================================================================

    def _should_notify(self, alert: Alert) -> bool:
        """
        Determine if alert should be sent based on current conditions.

        Respects quiet mode (only CRITICAL alerts break silence) and
        debouncing (don't re-send same alert within debounce window).

        Args:
            alert: Alert to check.

        Returns:
            True if alert should be sent, False otherwise.
        """
        # In quiet mode, only CRITICAL alerts break silence
        if self._quiet_mode and alert.priority != AlertPriority.CRITICAL:
            return False

        # Check debouncing
        return not self._recently_sent(alert)

    def _recently_sent(self, alert: Alert) -> bool:
        """
        Check if a similar alert was recently sent.

        Uses alert type + entity UUID as the key for deduplication.

        Args:
            alert: Alert to check.

        Returns:
            True if alert was recently sent, False otherwise.
        """
        key = f"{alert.alert_type.value}:{alert.entity_uuid or 'none'}"
        last_sent = self._recent_alerts.get(key)

        if last_sent is None:
            return False

        debounce_seconds = self.officer_config.alert_debounce_minutes * 60
        elapsed = (datetime.now() - last_sent).total_seconds()

        return elapsed < debounce_seconds

    def _mark_alert_sent(self, alert: Alert) -> None:
        """
        Mark an alert as sent for debouncing.

        Args:
            alert: Alert that was sent.
        """
        key = f"{alert.alert_type.value}:{alert.entity_uuid or 'none'}"
        self._recent_alerts[key] = datetime.now()

    def clear_recent_alerts(self) -> None:
        """Clear the recent alerts cache (useful for testing)."""
        self._recent_alerts = {}

    # =========================================================================
    # Statistics
    # =========================================================================

    async def get_alert_statistics(
        self,
        trace_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Get statistics about current alert conditions.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            Dictionary with alert statistics.
        """
        # Count tasks by status and deadline proximity
        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
        RETURN
            count(t) as total_tasks,
            sum(CASE WHEN t.due_date IS NOT NULL AND t.due_date < timestamp()
                THEN 1 ELSE 0 END) as overdue_count,
            sum(CASE WHEN t.due_date IS NOT NULL
                AND t.due_date > timestamp()
                AND t.due_date <= timestamp() + 86400000
                THEN 1 ELSE 0 END) as due_24h_count,
            sum(CASE WHEN t.due_date IS NOT NULL
                AND t.due_date > timestamp() + 86400000
                AND t.due_date <= timestamp() + 604800000
                THEN 1 ELSE 0 END) as due_week_count
        """

        task_result = await self.neo4j.execute_query(query, {}, trace_id=trace_id)
        task_stats = task_result[0] if task_result else {}

        # Count upcoming events
        event_query = """
        MATCH (e:Event)
        WHERE e.start_time > timestamp()
          AND e.start_time <= timestamp() + 86400000
          AND e.expired_at IS NULL
        RETURN count(e) as events_24h
        """

        event_result = await self.neo4j.execute_query(event_query, {}, trace_id=trace_id)
        event_stats = event_result[0] if event_result else {}

        return {
            "total_active_tasks": task_stats.get("total_tasks", 0),
            "overdue_tasks": task_stats.get("overdue_count", 0),
            "tasks_due_24h": task_stats.get("due_24h_count", 0),
            "tasks_due_week": task_stats.get("due_week_count", 0),
            "events_24h": event_stats.get("events_24h", 0),
            "quiet_mode": self._quiet_mode,
            "cached_alerts": len(self._recent_alerts),
        }


# =============================================================================
# Export
# =============================================================================

__all__ = [
    "Alert",
    "AlertCheckResult",
    "AlertPriority",
    "AlertType",
    "OfficerConfig",
    "OfficerOfTheWatch",
]
