"""
OfficerOfTheWatch agent for Klabautermann.

Proactive alert and monitoring agent that watches for conditions warranting
notification - approaching deadlines, upcoming meetings, schedule conflicts,
and unusual patterns. Respects "quiet mode" during focused work periods.

Reference: specs/architecture/AGENTS_EXTENDED.md Section 3
Issues: #59, #60, #61
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING, Any

from klabautermann.agents.base_agent import BaseAgent
from klabautermann.core.logger import logger
from klabautermann.core.models import AgentMessage


if TYPE_CHECKING:
    from klabautermann.channels.manager import BroadcastResult, ChannelManager
    from klabautermann.memory.neo4j_client import Neo4jClient


# =============================================================================
# Configuration
# =============================================================================


class AlertPriority(str, Enum):
    """Priority levels for alerts."""

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    """Types of alerts the Officer can generate."""

    MORNING_BRIEFING = "morning_briefing"
    DEADLINE_WARNING = "deadline_warning"
    MEETING_REMINDER = "meeting_reminder"
    SCHEDULE_CONFLICT = "schedule_conflict"
    OVERDUE_TASK = "overdue_task"
    ANOMALY = "anomaly"


@dataclass
class OfficerConfig:
    """Configuration for OfficerOfTheWatch agent."""

    # Timing thresholds
    deadline_warning_hours: int = 24  # Warn when task due within N hours
    meeting_reminder_minutes: int = 15  # Remind N minutes before meeting

    # Morning briefing
    briefing_hour: int = 7  # Hour (0-23) to generate morning briefing
    briefing_minute: int = 0  # Minute (0-59)
    briefing_look_ahead_days: int = 1  # Days to look ahead for events/tasks

    # Deep Work detection
    deep_work_keywords: list[str] = field(
        default_factory=lambda: ["Deep Work", "Focus", "Do Not Disturb"]
    )

    # Alert limits
    max_alerts_per_check: int = 10
    alert_debounce_minutes: int = 60  # Don't re-send same alert within N minutes

    # Query limits
    default_query_limit: int = 50


@dataclass
class Alert:
    """A single alert generated by the Officer."""

    alert_type: AlertType
    priority: AlertPriority
    message: str
    entity_uuid: str | None = None
    entity_type: str | None = None
    due_at: int | None = None  # Unix timestamp (milliseconds)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "alert_type": self.alert_type.value,
            "priority": self.priority.value,
            "message": self.message,
            "entity_uuid": self.entity_uuid,
            "entity_type": self.entity_type,
            "due_at": self.due_at,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class AlertCheckResult:
    """Result of an alert check operation."""

    alerts_found: int
    alerts_sent: int
    quiet_mode: bool
    deep_work_event: str | None
    duration_ms: float
    alerts: list[Alert] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alerts_found": self.alerts_found,
            "alerts_sent": self.alerts_sent,
            "quiet_mode": self.quiet_mode,
            "deep_work_event": self.deep_work_event,
            "duration_ms": round(self.duration_ms, 2),
            "alerts": [a.to_dict() for a in self.alerts],
        }


@dataclass
class CalendarEventSummary:
    """Summary of a calendar event for morning briefing."""

    uuid: str
    title: str
    start_time: int  # Unix timestamp (ms)
    end_time: int  # Unix timestamp (ms)
    location: str | None = None
    description: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "uuid": self.uuid,
            "title": self.title,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "location": self.location,
            "description": self.description,
        }


@dataclass
class TaskSummary:
    """Summary of a task for morning briefing."""

    uuid: str
    action: str
    priority: str
    status: str
    due_date: int | None = None  # Unix timestamp (ms)
    project_name: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "uuid": self.uuid,
            "action": self.action,
            "priority": self.priority,
            "status": self.status,
            "due_date": self.due_date,
            "project_name": self.project_name,
        }


@dataclass
class MorningBriefing:
    """Morning briefing summary with schedule, tasks, and alerts."""

    generated_at: datetime
    greeting: str
    events_today: list[CalendarEventSummary]
    high_priority_tasks: list[TaskSummary]
    overdue_tasks: list[TaskSummary]
    overnight_alerts: list[Alert]
    summary_text: str
    duration_ms: float

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "generated_at": self.generated_at.isoformat(),
            "greeting": self.greeting,
            "events_today": [e.to_dict() for e in self.events_today],
            "high_priority_tasks": [t.to_dict() for t in self.high_priority_tasks],
            "overdue_tasks": [t.to_dict() for t in self.overdue_tasks],
            "overnight_alerts": [a.to_dict() for a in self.overnight_alerts],
            "summary_text": self.summary_text,
            "duration_ms": round(self.duration_ms, 2),
        }


@dataclass
class AlertSendResult:
    """Result of sending alerts to channels.

    Tracks which channels received alerts and any failures that occurred.
    Issue: #67
    """

    alerts_sent: int
    channels_delivered: list[str]
    channels_failed: list[str]
    errors: dict[str, str]  # channel_name -> error message

    @property
    def all_delivered(self) -> bool:
        """Check if all channels received the alerts."""
        return len(self.channels_failed) == 0

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "alerts_sent": self.alerts_sent,
            "channels_delivered": self.channels_delivered,
            "channels_failed": self.channels_failed,
            "errors": self.errors,
            "all_delivered": self.all_delivered,
        }


# =============================================================================
# OfficerOfTheWatch Agent
# =============================================================================


class OfficerOfTheWatch(BaseAgent):
    """
    Proactive alert and monitoring agent.

    The Officer monitors conditions that warrant proactive notification -
    approaching deadlines, upcoming meetings, schedule conflicts, and
    unusual patterns. Respects "quiet mode" during focused work periods.
    """

    def __init__(
        self,
        neo4j_client: Neo4jClient,
        config: OfficerConfig | None = None,
        channel_manager: ChannelManager | None = None,
    ) -> None:
        """
        Initialize OfficerOfTheWatch.

        Args:
            neo4j_client: Connected Neo4j client for graph operations.
            config: Optional configuration for alert behavior.
            channel_manager: Optional channel manager for sending alerts.
                            If provided, enables send_alerts_to_channels().
        """
        super().__init__(name="officer_of_the_watch")
        self.neo4j = neo4j_client
        self.officer_config = config or OfficerConfig()
        self._channel_manager = channel_manager

        # Track recently sent alerts for debouncing
        self._recent_alerts: dict[str, datetime] = {}

        # Current quiet mode state
        self._quiet_mode = False
        self._current_deep_work_event: str | None = None

    async def process_message(self, msg: AgentMessage) -> AgentMessage | None:
        """
        Process an incoming message.

        OfficerOfTheWatch responds to monitoring and alert commands.

        Args:
            msg: The incoming agent message.

        Returns:
            Response message with alert results.
        """
        trace_id = msg.trace_id
        payload = msg.payload or {}

        operation = payload.get("operation", "check_conditions")

        logger.info(
            f"[CHART] OfficerOfTheWatch processing {operation}",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        if operation == "check_conditions":
            result = await self.check_conditions(trace_id=trace_id)
            result_payload = result.to_dict()
        elif operation == "check_deadlines":
            alerts = await self.check_upcoming_deadlines(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "check_meetings":
            alerts = await self.check_upcoming_meetings(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "check_overdue":
            alerts = await self.check_overdue_tasks(trace_id=trace_id)
            result_payload = {
                "alerts": [a.to_dict() for a in alerts],
                "count": len(alerts),
            }
        elif operation == "is_deep_work":
            is_deep_work = await self.is_deep_work_time(trace_id=trace_id)
            result_payload = {
                "is_deep_work": is_deep_work,
                "deep_work_event": self._current_deep_work_event,
            }
        elif operation == "morning_briefing":
            briefing = await self.generate_morning_briefing(trace_id=trace_id)
            result_payload = briefing.to_dict()
        elif operation == "send_alerts":
            # Send provided alerts to all channels
            alerts_data = payload.get("alerts", [])
            alerts = [
                Alert(
                    alert_type=AlertType(a["alert_type"]),
                    priority=AlertPriority(a["priority"]),
                    message=a["message"],
                    entity_uuid=a.get("entity_uuid"),
                    entity_type=a.get("entity_type"),
                    due_at=a.get("due_at"),
                    metadata=a.get("metadata", {}),
                )
                for a in alerts_data
            ]
            send_result = await self.send_alerts_to_channels(
                alerts=alerts, trace_id=trace_id
            )
            result_payload = send_result.to_dict()
        else:
            result_payload = {"error": f"Unknown operation: {operation}"}

        return AgentMessage(
            source_agent=self.name,
            target_agent=msg.source_agent,
            intent="officer_result",
            payload=result_payload,
            trace_id=trace_id,
        )

    # =========================================================================
    # Main Operations
    # =========================================================================

    async def check_conditions(
        self,
        trace_id: str | None = None,
    ) -> AlertCheckResult:
        """
        Main monitoring routine - check all alert conditions.

        This is the primary entry point called by scheduler.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            AlertCheckResult with all generated alerts.
        """
        start_time = time.time()
        all_alerts: list[Alert] = []

        logger.info(
            "[CHART] Officer checking conditions",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        # Check if in quiet mode (Deep Work time)
        self._quiet_mode = await self.is_deep_work_time(trace_id=trace_id)

        if self._quiet_mode:
            logger.info(
                f"[WHISPER] Quiet mode active: {self._current_deep_work_event}",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )

        # Run all checks
        deadline_alerts = await self.check_upcoming_deadlines(trace_id=trace_id)
        all_alerts.extend(deadline_alerts)

        meeting_alerts = await self.check_upcoming_meetings(trace_id=trace_id)
        all_alerts.extend(meeting_alerts)

        overdue_alerts = await self.check_overdue_tasks(trace_id=trace_id)
        all_alerts.extend(overdue_alerts)

        # Filter by quiet mode and debouncing
        alerts_to_send: list[Alert] = []
        for alert in all_alerts:
            if self._should_notify(alert):
                alerts_to_send.append(alert)
                self._mark_alert_sent(alert)

        # Limit alerts per check
        alerts_to_send = alerts_to_send[: self.officer_config.max_alerts_per_check]

        duration_ms = (time.time() - start_time) * 1000

        result = AlertCheckResult(
            alerts_found=len(all_alerts),
            alerts_sent=len(alerts_to_send),
            quiet_mode=self._quiet_mode,
            deep_work_event=self._current_deep_work_event,
            duration_ms=duration_ms,
            alerts=alerts_to_send,
        )

        logger.info(
            f"[BEACON] Officer check complete: "
            f"found {len(all_alerts)} alerts, sending {len(alerts_to_send)} "
            f"(quiet_mode={self._quiet_mode})",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return result

    # =========================================================================
    # Morning Briefing (#4)
    # =========================================================================

    async def generate_morning_briefing(
        self,
        trace_id: str | None = None,
    ) -> MorningBriefing:
        """
        Generate a proactive morning briefing with schedule, tasks, and alerts.

        The morning briefing includes:
        - Today's calendar events
        - High-priority tasks (urgent/high)
        - Overdue tasks
        - Any overnight alerts

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            MorningBriefing with all relevant information.
        """
        start_time = time.time()

        logger.info(
            "[CHART] Generating morning briefing",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        # Get today's events
        events_today = await self._get_todays_events(trace_id=trace_id)

        # Get high-priority tasks
        high_priority_tasks = await self._get_high_priority_tasks(trace_id=trace_id)

        # Get overdue tasks
        overdue_tasks = await self._get_overdue_tasks_for_briefing(trace_id=trace_id)

        # Get overnight alerts (any alerts generated in last 12 hours)
        overnight_alerts = await self._get_overnight_alerts(trace_id=trace_id)

        # Generate greeting based on time and workload
        greeting = self._generate_greeting(
            event_count=len(events_today),
            task_count=len(high_priority_tasks),
            overdue_count=len(overdue_tasks),
        )

        # Generate summary text
        summary_text = self._generate_summary_text(
            events=events_today,
            high_priority=high_priority_tasks,
            overdue=overdue_tasks,
            alerts=overnight_alerts,
        )

        duration_ms = (time.time() - start_time) * 1000

        briefing = MorningBriefing(
            generated_at=datetime.now(),
            greeting=greeting,
            events_today=events_today,
            high_priority_tasks=high_priority_tasks,
            overdue_tasks=overdue_tasks,
            overnight_alerts=overnight_alerts,
            summary_text=summary_text,
            duration_ms=duration_ms,
        )

        logger.info(
            f"[BEACON] Morning briefing generated: "
            f"{len(events_today)} events, {len(high_priority_tasks)} high-priority tasks, "
            f"{len(overdue_tasks)} overdue",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return briefing

    async def _get_todays_events(
        self,
        trace_id: str | None = None,
    ) -> list[CalendarEventSummary]:
        """Get all calendar events for today."""
        # Calculate today's time bounds (midnight to midnight)
        now = datetime.now()
        today_start = datetime(now.year, now.month, now.day)
        today_end = today_start.replace(hour=23, minute=59, second=59)

        today_start_ms = int(today_start.timestamp() * 1000)
        today_end_ms = int(today_end.timestamp() * 1000)

        query = """
        MATCH (e:Event)
        WHERE e.start_time >= $start_ms
          AND e.start_time <= $end_ms
          AND e.expired_at IS NULL
        RETURN e.uuid as uuid, e.title as title, e.start_time as start_time,
               e.end_time as end_time, e.location_context as location,
               e.description as description
        ORDER BY e.start_time ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {
                "start_ms": today_start_ms,
                "end_ms": today_end_ms,
                "limit": self.officer_config.default_query_limit,
            },
            trace_id=trace_id,
        )

        events = []
        for row in results:
            event = CalendarEventSummary(
                uuid=row.get("uuid", ""),
                title=row.get("title", "Unknown Event"),
                start_time=row.get("start_time", 0),
                end_time=row.get("end_time", 0),
                location=row.get("location"),
                description=row.get("description"),
            )
            events.append(event)

        return events

    async def _get_high_priority_tasks(
        self,
        trace_id: str | None = None,
    ) -> list[TaskSummary]:
        """Get high-priority tasks (urgent or high priority)."""
        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.priority IN ['urgent', 'high']
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.priority as priority,
               t.status as status, t.due_date as due_date, p.name as project_name
        ORDER BY
            CASE t.priority WHEN 'urgent' THEN 0 ELSE 1 END,
            t.due_date ASC NULLS LAST
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {"limit": self.officer_config.default_query_limit},
            trace_id=trace_id,
        )

        tasks = []
        for row in results:
            task = TaskSummary(
                uuid=row.get("uuid", ""),
                action=row.get("action", "Unknown Task"),
                priority=row.get("priority", "medium"),
                status=row.get("status", "todo"),
                due_date=row.get("due_date"),
                project_name=row.get("project_name"),
            )
            tasks.append(task)

        return tasks

    async def _get_overdue_tasks_for_briefing(
        self,
        trace_id: str | None = None,
    ) -> list[TaskSummary]:
        """Get overdue tasks for the briefing."""
        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.due_date IS NOT NULL
          AND t.due_date < timestamp()
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.priority as priority,
               t.status as status, t.due_date as due_date, p.name as project_name
        ORDER BY t.due_date ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {"limit": self.officer_config.default_query_limit},
            trace_id=trace_id,
        )

        tasks = []
        for row in results:
            task = TaskSummary(
                uuid=row.get("uuid", ""),
                action=row.get("action", "Unknown Task"),
                priority=row.get("priority", "medium"),
                status=row.get("status", "todo"),
                due_date=row.get("due_date"),
                project_name=row.get("project_name"),
            )
            tasks.append(task)

        return tasks

    async def _get_overnight_alerts(
        self,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Get alerts that would have been generated overnight.

        This re-runs the alert checks to find any conditions
        that accumulated overnight.
        """
        # Get deadline warnings and overdue tasks
        deadline_alerts = await self.check_upcoming_deadlines(trace_id=trace_id)
        overdue_alerts = await self.check_overdue_tasks(trace_id=trace_id)

        # Combine and limit
        all_alerts = deadline_alerts + overdue_alerts
        return all_alerts[: self.officer_config.max_alerts_per_check]

    def _generate_greeting(
        self,
        event_count: int,
        task_count: int,
        overdue_count: int,
    ) -> str:
        """Generate a nautical greeting based on the day's outlook."""
        now = datetime.now()
        hour = now.hour

        # Time-based greeting
        if hour < 12:
            time_greeting = "Good morning, Captain"
        elif hour < 17:
            time_greeting = "Good afternoon, Captain"
        else:
            time_greeting = "Good evening, Captain"

        # Workload assessment
        total_items = event_count + task_count
        if overdue_count > 0:
            outlook = "There are overdue items requiring attention."
        elif total_items == 0:
            outlook = "Clear skies ahead - no events or urgent tasks today."
        elif total_items <= 3:
            outlook = "Calm seas - a manageable day ahead."
        elif total_items <= 6:
            outlook = "Moderate winds - a full but manageable schedule."
        else:
            outlook = "Choppy waters - a busy day ahead. Steady as she goes."

        return f"{time_greeting}. {outlook}"

    def _generate_summary_text(
        self,
        events: list[CalendarEventSummary],
        high_priority: list[TaskSummary],
        overdue: list[TaskSummary],
        alerts: list[Alert],
    ) -> str:
        """Generate a human-readable summary of the morning briefing."""
        lines = []

        # Events summary
        if events:
            lines.append(f"**Schedule**: {len(events)} event(s) today")
            for event in events[:5]:  # Limit display
                start_dt = datetime.fromtimestamp(event.start_time / 1000)
                time_str = start_dt.strftime("%H:%M")
                location = f" at {event.location}" if event.location else ""
                lines.append(f"  - {time_str}: {event.title}{location}")
            if len(events) > 5:
                lines.append(f"  - ... and {len(events) - 5} more")
        else:
            lines.append("**Schedule**: No events today")

        lines.append("")

        # High-priority tasks
        if high_priority:
            lines.append(f"**High Priority Tasks**: {len(high_priority)} task(s)")
            for task in high_priority[:5]:
                priority_marker = "[!]" if task.priority == "urgent" else "[H]"
                project = f" ({task.project_name})" if task.project_name else ""
                lines.append(f"  - {priority_marker} {task.action}{project}")
            if len(high_priority) > 5:
                lines.append(f"  - ... and {len(high_priority) - 5} more")
        else:
            lines.append("**High Priority Tasks**: None")

        lines.append("")

        # Overdue tasks
        if overdue:
            lines.append(f"**Overdue**: {len(overdue)} task(s) past due")
            for task in overdue[:3]:
                due_dt = datetime.fromtimestamp(task.due_date / 1000) if task.due_date else None
                due_str = f" (due {due_dt.strftime('%Y-%m-%d')})" if due_dt else ""
                lines.append(f"  - {task.action}{due_str}")
            if len(overdue) > 3:
                lines.append(f"  - ... and {len(overdue) - 3} more")
        else:
            lines.append("**Overdue**: All clear")

        # Alerts
        if alerts:
            lines.append("")
            lines.append(f"**Alerts**: {len(alerts)} item(s) need attention")

        return "\n".join(lines)

    def is_briefing_time(self) -> bool:
        """
        Check if current time matches the configured briefing time.

        Returns:
            True if it's briefing time, False otherwise.
        """
        now = datetime.now()
        return (
            now.hour == self.officer_config.briefing_hour
            and now.minute == self.officer_config.briefing_minute
        )

    # =========================================================================
    # Deep Work Detection
    # =========================================================================

    async def is_deep_work_time(
        self,
        trace_id: str | None = None,
    ) -> bool:
        """
        Check if the Captain is currently in a Deep Work calendar block.

        Deep Work events are detected by title keywords like "Deep Work",
        "Focus", or "Do Not Disturb".

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            True if in deep work mode, False otherwise.
        """
        keywords = self.officer_config.deep_work_keywords
        # Build regex pattern for keywords
        keyword_pattern = "|".join(keywords)

        query = """
        MATCH (e:Event)
        WHERE e.start_time <= timestamp()
          AND e.end_time >= timestamp()
          AND e.expired_at IS NULL
          AND e.title =~ $pattern
        RETURN e.uuid as uuid, e.title as title
        LIMIT 1
        """

        result = await self.neo4j.execute_query(
            query,
            {"pattern": f"(?i).*({keyword_pattern}).*"},
            trace_id=trace_id,
        )

        if result:
            self._current_deep_work_event = result[0].get("title")
            return True

        self._current_deep_work_event = None
        return False

    # =========================================================================
    # Deadline Alerts (#60)
    # =========================================================================

    async def check_upcoming_deadlines(
        self,
        hours: int | None = None,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find tasks due within the specified time window.

        Generates WARNING alerts for high-priority tasks and INFO alerts
        for normal priority tasks.

        Args:
            hours: Hours until deadline (default from config).
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for upcoming deadlines.
        """
        hours = hours or self.officer_config.deadline_warning_hours
        hours_ms = hours * 60 * 60 * 1000  # Convert to milliseconds

        logger.debug(
            f"[WHISPER] Checking deadlines within {hours} hours",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.due_date IS NOT NULL
          AND t.due_date <= timestamp() + $hours_ms
          AND t.due_date > timestamp()
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.due_date as due_date,
               t.priority as priority, t.status as status,
               p.name as project_name
        ORDER BY t.due_date ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {
                "hours_ms": hours_ms,
                "limit": self.officer_config.default_query_limit,
            },
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            priority = row.get("priority", "medium")
            alert_priority = (
                AlertPriority.WARNING if priority in ("urgent", "high") else AlertPriority.INFO
            )

            # Calculate hours remaining
            due_date = row.get("due_date", 0)
            now_ms = int(time.time() * 1000)
            hours_remaining = (due_date - now_ms) / (60 * 60 * 1000)

            message = f"Task due in {hours_remaining:.1f}h: {row.get('action', 'Unknown task')}"
            if row.get("project_name"):
                message += f" ({row['project_name']})"

            alert = Alert(
                alert_type=AlertType.DEADLINE_WARNING,
                priority=alert_priority,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Task",
                due_at=due_date,
                metadata={
                    "task_action": row.get("action"),
                    "task_priority": priority,
                    "task_status": row.get("status"),
                    "project_name": row.get("project_name"),
                    "hours_remaining": round(hours_remaining, 1),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} deadline warnings",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Meeting Reminders (#61)
    # =========================================================================

    async def check_upcoming_meetings(
        self,
        minutes: int | None = None,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find meetings starting within the specified time window.

        Generates INFO alerts for upcoming meetings with event details.

        Args:
            minutes: Minutes until meeting (default from config).
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for upcoming meetings.
        """
        minutes = minutes or self.officer_config.meeting_reminder_minutes
        minutes_ms = minutes * 60 * 1000  # Convert to milliseconds

        logger.debug(
            f"[WHISPER] Checking meetings within {minutes} minutes",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (e:Event)
        WHERE e.start_time <= timestamp() + $minutes_ms
          AND e.start_time > timestamp()
          AND e.expired_at IS NULL
        RETURN e.uuid as uuid, e.title as title, e.start_time as start_time,
               e.end_time as end_time, e.location_context as location,
               e.description as description
        ORDER BY e.start_time ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {
                "minutes_ms": minutes_ms,
                "limit": self.officer_config.default_query_limit,
            },
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            # Calculate minutes remaining
            start_time = row.get("start_time", 0)
            now_ms = int(time.time() * 1000)
            minutes_remaining = (start_time - now_ms) / (60 * 1000)

            message = (
                f"Meeting in {minutes_remaining:.0f}min: {row.get('title', 'Unknown meeting')}"
            )
            if row.get("location"):
                message += f" at {row['location']}"

            alert = Alert(
                alert_type=AlertType.MEETING_REMINDER,
                priority=AlertPriority.INFO,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Event",
                due_at=start_time,
                metadata={
                    "event_title": row.get("title"),
                    "event_location": row.get("location"),
                    "event_description": row.get("description"),
                    "start_time": start_time,
                    "end_time": row.get("end_time"),
                    "minutes_remaining": round(minutes_remaining, 0),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} meeting reminders",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Overdue Tasks
    # =========================================================================

    async def check_overdue_tasks(
        self,
        trace_id: str | None = None,
    ) -> list[Alert]:
        """
        Find tasks that are past their due date.

        Generates ERROR alerts for overdue tasks.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            List of Alert objects for overdue tasks.
        """
        logger.debug(
            "[WHISPER] Checking overdue tasks",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
          AND t.due_date IS NOT NULL
          AND t.due_date < timestamp()
        OPTIONAL MATCH (t)-[:PART_OF]->(p:Project)
        RETURN t.uuid as uuid, t.action as action, t.due_date as due_date,
               t.priority as priority, t.status as status,
               p.name as project_name
        ORDER BY t.due_date ASC
        LIMIT $limit
        """

        results = await self.neo4j.execute_query(
            query,
            {"limit": self.officer_config.default_query_limit},
            trace_id=trace_id,
        )

        alerts: list[Alert] = []
        for row in results:
            # Calculate hours overdue
            due_date = row.get("due_date", 0)
            now_ms = int(time.time() * 1000)
            hours_overdue = (now_ms - due_date) / (60 * 60 * 1000)

            message = f"Task overdue by {hours_overdue:.1f}h: {row.get('action', 'Unknown task')}"
            if row.get("project_name"):
                message += f" ({row['project_name']})"

            alert = Alert(
                alert_type=AlertType.OVERDUE_TASK,
                priority=AlertPriority.ERROR,
                message=message,
                entity_uuid=row.get("uuid"),
                entity_type="Task",
                due_at=due_date,
                metadata={
                    "task_action": row.get("action"),
                    "task_priority": row.get("priority"),
                    "task_status": row.get("status"),
                    "project_name": row.get("project_name"),
                    "hours_overdue": round(hours_overdue, 1),
                },
            )
            alerts.append(alert)

        logger.debug(
            f"[WHISPER] Found {len(alerts)} overdue tasks",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        return alerts

    # =========================================================================
    # Alert Filtering and Debouncing
    # =========================================================================

    def _should_notify(self, alert: Alert) -> bool:
        """
        Determine if alert should be sent based on current conditions.

        Respects quiet mode (only CRITICAL alerts break silence) and
        debouncing (don't re-send same alert within debounce window).

        Args:
            alert: Alert to check.

        Returns:
            True if alert should be sent, False otherwise.
        """
        # In quiet mode, only CRITICAL alerts break silence
        if self._quiet_mode and alert.priority != AlertPriority.CRITICAL:
            return False

        # Check debouncing
        return not self._recently_sent(alert)

    def _recently_sent(self, alert: Alert) -> bool:
        """
        Check if a similar alert was recently sent.

        Uses alert type + entity UUID as the key for deduplication.

        Args:
            alert: Alert to check.

        Returns:
            True if alert was recently sent, False otherwise.
        """
        key = f"{alert.alert_type.value}:{alert.entity_uuid or 'none'}"
        last_sent = self._recent_alerts.get(key)

        if last_sent is None:
            return False

        debounce_seconds = self.officer_config.alert_debounce_minutes * 60
        elapsed = (datetime.now() - last_sent).total_seconds()

        return elapsed < debounce_seconds

    def _mark_alert_sent(self, alert: Alert) -> None:
        """
        Mark an alert as sent for debouncing.

        Args:
            alert: Alert that was sent.
        """
        key = f"{alert.alert_type.value}:{alert.entity_uuid or 'none'}"
        self._recent_alerts[key] = datetime.now()

    def clear_recent_alerts(self) -> None:
        """Clear the recent alerts cache (useful for testing)."""
        self._recent_alerts = {}

    # =========================================================================
    # Statistics
    # =========================================================================

    async def get_alert_statistics(
        self,
        trace_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Get statistics about current alert conditions.

        Args:
            trace_id: Optional trace ID for logging.

        Returns:
            Dictionary with alert statistics.
        """
        # Count tasks by status and deadline proximity
        query = """
        MATCH (t:Task)
        WHERE t.status IN ['todo', 'in_progress']
        RETURN
            count(t) as total_tasks,
            sum(CASE WHEN t.due_date IS NOT NULL AND t.due_date < timestamp()
                THEN 1 ELSE 0 END) as overdue_count,
            sum(CASE WHEN t.due_date IS NOT NULL
                AND t.due_date > timestamp()
                AND t.due_date <= timestamp() + 86400000
                THEN 1 ELSE 0 END) as due_24h_count,
            sum(CASE WHEN t.due_date IS NOT NULL
                AND t.due_date > timestamp() + 86400000
                AND t.due_date <= timestamp() + 604800000
                THEN 1 ELSE 0 END) as due_week_count
        """

        task_result = await self.neo4j.execute_query(query, {}, trace_id=trace_id)
        task_stats = task_result[0] if task_result else {}

        # Count upcoming events
        event_query = """
        MATCH (e:Event)
        WHERE e.start_time > timestamp()
          AND e.start_time <= timestamp() + 86400000
          AND e.expired_at IS NULL
        RETURN count(e) as events_24h
        """

        event_result = await self.neo4j.execute_query(event_query, {}, trace_id=trace_id)
        event_stats = event_result[0] if event_result else {}

        return {
            "total_active_tasks": task_stats.get("total_tasks", 0),
            "overdue_tasks": task_stats.get("overdue_count", 0),
            "tasks_due_24h": task_stats.get("due_24h_count", 0),
            "tasks_due_week": task_stats.get("due_week_count", 0),
            "events_24h": event_stats.get("events_24h", 0),
            "quiet_mode": self._quiet_mode,
            "cached_alerts": len(self._recent_alerts),
        }

    # =========================================================================
    # Channel Integration (#67)
    # =========================================================================

    def format_alert_for_channel(
        self,
        alert: Alert,
        channel_type: str | None = None,
    ) -> str:
        """
        Format an alert for display on a specific channel type.

        Formats alerts with appropriate styling for different channels:
        - CLI: Uses emoji prefixes and Markdown formatting for Rich rendering
        - Telegram: Uses Markdown with emoji prefixes suitable for Telegram

        Args:
            alert: The alert to format.
            channel_type: The type of channel ('cli', 'telegram', etc.).
                         If None, uses a generic format.

        Returns:
            Formatted alert string.
        """
        # Priority emoji prefixes
        priority_emoji = {
            AlertPriority.CRITICAL: "🚨",
            AlertPriority.ERROR: "❌",
            AlertPriority.WARNING: "⚠️",
            AlertPriority.INFO: "ℹ️",  # noqa: RUF001
        }

        # Alert type labels
        type_labels = {
            AlertType.DEADLINE_WARNING: "Deadline",
            AlertType.MEETING_REMINDER: "Meeting",
            AlertType.OVERDUE_TASK: "Overdue",
            AlertType.SCHEDULE_CONFLICT: "Conflict",
            AlertType.ANOMALY: "Alert",
            AlertType.MORNING_BRIEFING: "Briefing",
        }

        emoji = priority_emoji.get(alert.priority, "📢")
        label = type_labels.get(alert.alert_type, "Alert")

        # Format depends on channel type
        if channel_type == "telegram":
            # Telegram Markdown format
            return f"{emoji} *{label}*: {alert.message}"
        elif channel_type == "cli":
            # Rich Markdown format
            return f"{emoji} **{label}**: {alert.message}"
        else:
            # Generic format
            return f"{emoji} [{label}] {alert.message}"

    async def send_alerts_to_channels(
        self,
        alerts: list[Alert],
        trace_id: str | None = None,
    ) -> AlertSendResult:
        """
        Send alerts to all active channels via the Channel Manager.

        This method broadcasts alerts to all active channels, formatting
        each alert appropriately for the channel type. Failures on individual
        channels do not prevent delivery to other channels.

        Args:
            alerts: List of alerts to send.
            trace_id: Optional trace ID for logging.

        Returns:
            AlertSendResult with delivery status per channel.

        Raises:
            ValueError: If no channel manager is configured.
        """
        if self._channel_manager is None:
            logger.warning(
                "[SWELL] Cannot send alerts: no channel manager configured",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )
            return AlertSendResult(
                alerts_sent=0,
                channels_delivered=[],
                channels_failed=[],
                errors={"_config": "No channel manager configured"},
            )

        if not alerts:
            logger.debug(
                "[WHISPER] No alerts to send",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )
            return AlertSendResult(
                alerts_sent=0,
                channels_delivered=[],
                channels_failed=[],
                errors={},
            )

        logger.info(
            f"[CHART] Sending {len(alerts)} alerts to channels",
            extra={"trace_id": trace_id, "agent_name": self.name},
        )

        # Get active channels to determine formatting
        active_channels = self._channel_manager.active_channels

        if not active_channels:
            logger.warning(
                "[SWELL] No active channels to send alerts to",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )
            return AlertSendResult(
                alerts_sent=0,
                channels_delivered=[],
                channels_failed=[],
                errors={"_channels": "No active channels"},
            )

        # Format alerts as a combined message (generic format for broadcast)
        formatted_lines = [
            self.format_alert_for_channel(alert, channel_type=None)
            for alert in alerts
        ]
        content = "\n".join(formatted_lines)

        # Broadcast to all active channels
        try:
            broadcast_result: BroadcastResult = await self._channel_manager.broadcast(
                content=content,
                metadata={"alert_count": len(alerts), "trace_id": trace_id},
            )

            logger.info(
                f"[BEACON] Alert broadcast complete: "
                f"{broadcast_result.delivered_count} delivered, "
                f"{broadcast_result.failed_count} failed",
                extra={"trace_id": trace_id, "agent_name": self.name},
            )

            return AlertSendResult(
                alerts_sent=len(alerts),
                channels_delivered=broadcast_result.channels_delivered,
                channels_failed=broadcast_result.channels_failed,
                errors=broadcast_result.errors,
            )

        except Exception as e:
            logger.error(
                f"[STORM] Failed to broadcast alerts: {e}",
                extra={"trace_id": trace_id, "agent_name": self.name},
                exc_info=True,
            )
            return AlertSendResult(
                alerts_sent=0,
                channels_delivered=[],
                channels_failed=active_channels,
                errors={"_broadcast": str(e)},
            )


# =============================================================================
# Export
# =============================================================================

__all__ = [
    "Alert",
    "AlertCheckResult",
    "AlertPriority",
    "AlertSendResult",
    "AlertType",
    "CalendarEventSummary",
    "MorningBriefing",
    "OfficerConfig",
    "OfficerOfTheWatch",
    "TaskSummary",
]
